theme = "assembly"
baseURL = "https://lifehack.nuscomputing.com"
languageCode = "en-US"
title = "Lifehack 2020"
publishDir = "docs"



# Metadata
[params]
  author = "Lifehack 2020"
  description = "Lifehack 2020"


[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

[params.nav]
  about = "About"
  timeline = "Timeline"
  workshops = "Workshops"
  prizes = "Prizes"
  judges = "Judges"
  register = "Registration"
  faq = "FAQ"
  contact = "Contact"


# About section
[params.about]
  enable = true
  title = "About"
  description = "Lifehack 2020 is a virtual datathon that invites you to apply data science to solve pertinent real world problems. Through wide-ranging workshops, you will be exposed to professional tools and develop advanced technical skills to provide innovative solutions for the healthcare industry."
  button_text = "Register Here"



# Timeline section
[params.timeline]
  enable = true
  title = "Timeline"


# Services section
[params.workshops]
  enable = true
  title = "Workshops"

  [[params.workshops.item1]]
    title = "Introduction to Neural Network"
    company = "IHiS"
    date = "Date TBC"
    time = "Time TBC"
    description = "For this workshop, we will explore the fundamentals of Neural Network and its learning function. We will demonstrate a simple example of  image recognition so that you can have a glimpse of the implementation of Neural Network using modern learning framework."

  [[params.workshops.item1]]
    title = "How to make a Data Science presentation for business?"
    company = "Holmusk"
    date = "Saturday, 18 Jul 2020"
    time = "6:00pm - 7:30pm"
    description = "Your findings may be groundbreaking, but will you be able to showcase their value to the judges? This workshop will cover fundamentals of presentations and how to present your data science findings in a business setting."

  [[params.workshops.item2]]
    title = "Python Basics for Data Science"
    company = "Smartcademy"
    date = "Monday, 13 Jul 2020"
    time = "7:30pm - 9:00pm"
    description = "This workshop will cover the environment set up and introduction to some of the key libraries which we use for data science in python. Participants are expected to have a basic understanding of python. "

  [[params.workshops.item2]]
    title = "Data Science Models For Beginners "
    company = "Smartcademy"
    date = "Wednesday, 15 Jul 2020"
    time = "7:30pm - 9:00pm"
    description = "This workshop will be an introduction to supervised learning models and how to implement these models using python. We will also touch on the importance of exploratory data analysis."

  [[params.workshops.item2]]
    title = "Advanced Data Science Models"
    company = "Smartcademy"
    date = "Friday, 17 Jul 2020"
    time = "7:30pm - 9:00pm"
    description = "This workshop will cover additional data science models you can use for supervised and unsupervised learning. We will also touch on some best practices to keep in mind when building your models."



# Prizes section
[params.prizes]
  enable = true
  title = "Prizes"

  [[params.prizes.item]]
    title = "Top prize"
    description1 = "2 x iPad (7th Gen) 128GB"
    description2 = "2 x Apple Pencil (1st Gen) 128GB"

  [[params.prizes.item]]
    title = "Second prize"
    description1 = "2 x Samsung Tab S6 Lite [Grey] 4+128GB Wi-Fi"

  [[params.prizes.item]]
    title = "Third prize"
    description1 = "2 x Seagate One Touch SSD 1TB (Black)"

  [[params.prizes.item]]
    title = "Honourable mentions"
    description1 = "Honourable mentions for Year 3&#47;4 submission will receive:"
    description2 = "2 x iPad (7th Gen) 128GB"

# Judges section
[params.judges]
  enable = true
  title = "Networking with Companies"
  subtitle = "Final Round - 30 July (Open to All)"

  [[params.judges.item]]
    thumbnail = "/images/ihis_alt.png"
    name = "Representative"
    affiliation = "IHiS"
    timing = "2:30pm"

  [[params.judges.item]]
    thumbnail = "/images/shopee.png"
    name = "Representative"
    affiliation = "Shopee"
    timing = "3:00pm"

  [[params.judges.item]]
    thumbnail = "/images/holmusk.png"
    name = "Representative"
    affiliation = "Holmusk"
    timing = "3:30pm"

# Register section
[params.register]
  enable = true
  title = "Registration Details"
  button_text = "Register Here"

# faq section
[params.faq]
  enable = true
  title = "FAQ"

  [[params.faq.item]]
    title = "Who can participate?"
    description = "Anyone currently pursuing Tertiary education."

  [[params.faq.item]]
    title = "I don’t have a team member. Can I still participate?"
    description = "Teams must have only 2 members. You may email us at lifehack@nuscomputing.com and we can try to match you up with someone."

  [[params.faq.item]]
    title = "How will the submissions be assessed?"
    description = "Submissions will be assessed by NUS Professors. Results will be released on 29th July. Selected finalist teams will be invited to present their solutions to judges on the Finale day on 30th July. Stay tuned until then!"

  [[params.faq.item]]
    title = "Must I be present for the zoom session if my team is shortlisted?"
    description = "At least one member of the team has to be present. If no members are available, the team will be disqualified."

  [[params.faq.item]]
    title = "Will COVID-19 affect the hackathon?"
    description = "Since this is a fully virtual hackathon, it is not affected by COVID-19. The timeline will proceed as per normal."

  [[params.faq.item]]
    title = "Do I need any technical experience or knowledge?"
    description = "Basic programming competencies are expected, else all are welcomed! We have problem statements and workshops ranging from basic to advanced levels."

  [[params.faq.item]]
    title = "My team has encountered a roadblock in our project, can I seek help?"
    description = "Yes! We have a forum where our Holmusk partners and Professors will be on standby to answer all your queries. You can access the forum [here](https://lifehack2020.freeforums.net)."

  [[params.faq.item]]
    title = "Can I use code I previously wrote?"
    description = "You are allowed to use previously written code. However, the copying of ideas and code is not allowed."

  [[params.faq.item]]
    title = "Are there any restrictions on platforms and languages which can be used?"
    description = "No, feel free to use any programming languages or technology you’re comfortable with!"

  [[params.faq.item]]
    title = "Who owns the intellectual property rights to my submission?"
    description = "For IP Rights agreement, please refer to this [IP rights Agreement](/documents/intellectual_property_rights.pdf)."

  [[params.faq.item]]
    title = "Where can I find Updates/Announcements?"
    description = "Join us in our Telegram channel [here](https://t.me/lifehack2020_official) for most recent updates!"


# Organizers section
[params.organizers]
  enable = true
  title = "Sponsors and Organizers"



# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  subtitle = "For further enquiries, kindly email lifehack@nuscomputing.com"

# Footer section
[params.footer]
  enable = true
  copy = "2020 &copy; NUS Students' Computing Club | All rights reserved | Adapted from the Assembly Theme"
  twitter = ""
  facebook = ""
  instagram = ""
